#pragma once

enum Terrain_Enum {ROAD, PLAIN, MOUNTAIN};
enum Unit_Enum {INFANTRY, MECH, ARTILLERY, TANK};
enum Building_Enum {HEADQUARTERS, BASE, CITY};


enum Cost_Enum {COST_INFANTRY = 1000, COST_MECH = 3000, COST_ARTILLERY = 7000, COST_TANK = 6000};